# Basic
title: 一片纸张
subtitle: 个人站
description: 小白日常
# 头像里面的标题
avatarTitle: idealcitier
# 头像里面的描述
avatarDesc: 日常
url: "http://idealcitier.github.io"

# Comment
comment:
    disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: 230587123 
    github: idealcitier
    # twitter: 
    mail: leeguo@163.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 3e78aa37aa0cb883fb7a746474b6572b

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
#    id: UA-84134159-3   
#    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章

#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
# gems: [jekyll-paginate,jekyll-sitemap]
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


